max_tokens_per_batch = 25000
label_smoothing = 0.1
max_epochs = 24
use_amp = true
backend = 'decentdp'

[decent]
topology = 'ring'

[optim]
name = "accum-adam"
lr = 0.0008
betas = [0.9, 0.999]
eps = 1e-9
accum_iter = 4

[model]
arch = "transformer"
d_model = 512
num_heads = 8
num_layers = 6
dim_feedforward = 2048
dropout = 0.1

[lr_scheduler]
type = 'inverse_sqrt'
warmup_steps = 4000
warmup_decay = 0.01

[log]
log_freq = 250
wandb_on = true
wandb_project = "decentdp-transformer"
checkpoint_freq = 1

[reproduce]
seed = 810975
