max_tokens_per_batch = 25000
label_smoothing = 0.1
max_epochs = 5
use_amp = false
backend = 'decentdp'

[decent]
topology = 'complete'

[optim]
name = "adam"
lr = 0.0025
betas = [0.974, 0.999]
eps = 1e-9

[model]
arch = "transformer"
d_model = 1024
num_heads = 16
num_layers = 6
dim_feedforward = 4096
dropout = 0.1

[lr_scheduler]
type = 'inverse_sqrt'
warmup_steps = 4000
warmup_decay = 0.01

[log]
log_freq = 250
wandb_on = true
wandb_project = "decentdp-transformer"
checkpoint_freq = 1

[reproduce]
seed = 810975
